/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/_docs'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DocsDocsRouteImport } from './routes/_docs/docs'
import { Route as DocsPlaygroundRouteImport } from './routes/_docs/playground'
import { Route as DocsSketchStylesRouteImport } from './routes/_docs/sketch-styles'
import { Route as DocsComponentsIndexRouteImport } from './routes/_docs/components/index'
import { Route as DocsComponentsNameRouteImport } from './routes/_docs/components/$name'
import { Route as ComponentsNameMdRouteImport } from './routes/components.$name.md'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDocsRoute = DocsDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPlaygroundRoute = DocsPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSketchStylesRoute = DocsSketchStylesRouteImport.update({
  id: '/sketch-styles',
  path: '/sketch-styles',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsIndexRoute = DocsComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsNameRoute = DocsComponentsNameRouteImport.update({
  id: '/components/$name',
  path: '/components/$name',
  getParentRoute: () => DocsRoute,
} as any)
const ComponentsNameMdRoute = ComponentsNameMdRouteImport.update({
  id: '/components/$name/md',
  path: '/components/$name/md',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs': typeof DocsDocsRoute
  '/playground': typeof DocsPlaygroundRoute
  '/sketch-styles': typeof DocsSketchStylesRoute
  '/components/$name': typeof DocsComponentsNameRoute
  '/components/$name/md': typeof ComponentsNameMdRoute
  '/components/': typeof DocsComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs': typeof DocsDocsRoute
  '/playground': typeof DocsPlaygroundRoute
  '/sketch-styles': typeof DocsSketchStylesRoute
  '/components/$name': typeof DocsComponentsNameRoute
  '/components/$name/md': typeof ComponentsNameMdRoute
  '/components': typeof DocsComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_docs': typeof DocsRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_docs/docs': typeof DocsDocsRoute
  '/_docs/playground': typeof DocsPlaygroundRoute
  '/_docs/sketch-styles': typeof DocsSketchStylesRoute
  '/_docs/components/$name': typeof DocsComponentsNameRoute
  '/components/$name/md': typeof ComponentsNameMdRoute
  '/_docs/components/': typeof DocsComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/docs'
    | '/playground'
    | '/sketch-styles'
    | '/components/$name'
    | '/components/$name/md'
    | '/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/docs'
    | '/playground'
    | '/sketch-styles'
    | '/components/$name'
    | '/components/$name/md'
    | '/components'
  id:
    | '__root__'
    | '/'
    | '/_docs'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_docs/docs'
    | '/_docs/playground'
    | '/_docs/sketch-styles'
    | '/_docs/components/$name'
    | '/components/$name/md'
    | '/_docs/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ComponentsNameMdRoute: typeof ComponentsNameMdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/docs': {
      id: '/_docs/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsDocsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/playground': {
      id: '/_docs/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof DocsPlaygroundRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/sketch-styles': {
      id: '/_docs/sketch-styles'
      path: '/sketch-styles'
      fullPath: '/sketch-styles'
      preLoaderRoute: typeof DocsSketchStylesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/components/': {
      id: '/_docs/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof DocsComponentsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/components/$name': {
      id: '/_docs/components/$name'
      path: '/components/$name'
      fullPath: '/components/$name'
      preLoaderRoute: typeof DocsComponentsNameRouteImport
      parentRoute: typeof DocsRoute
    }
    '/components/$name/md': {
      id: '/components/$name/md'
      path: '/components/$name/md'
      fullPath: '/components/$name/md'
      preLoaderRoute: typeof ComponentsNameMdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsDocsRoute: typeof DocsDocsRoute
  DocsPlaygroundRoute: typeof DocsPlaygroundRoute
  DocsSketchStylesRoute: typeof DocsSketchStylesRoute
  DocsComponentsNameRoute: typeof DocsComponentsNameRoute
  DocsComponentsIndexRoute: typeof DocsComponentsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsDocsRoute: DocsDocsRoute,
  DocsPlaygroundRoute: DocsPlaygroundRoute,
  DocsSketchStylesRoute: DocsSketchStylesRoute,
  DocsComponentsNameRoute: DocsComponentsNameRoute,
  DocsComponentsIndexRoute: DocsComponentsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ComponentsNameMdRoute: ComponentsNameMdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
